### ISSUE TITLE
update the program to a universal windows app and distribute via the windows/microsoft store

### ISSUE THREAD

**Issue by larsschellhas** [RobertKrajewski/Sync-my-L2P#111]

**Comment by larsschellhas** [comment]
with the new Windows 10 Fall Creators Update SDK it is now possible to pack and distribute Win32-apps with only a few clicks as appx via the store

**Comment by larsschellhas** [comment]
What do you think, if I would start to work on a port of Sync-my-L2P to the UWP and maybe via Xamarin to iOS and Android, too?

**Comment by mwkroening** [comment]
What would be the benefit of adding a native UWP port?
I suspect this could lead to fragmentation and thus to a much higher burden for the maintainers.

**Comment by larsschellhas** [comment]
There are multiple benefits to this. On the one hand there are the benefits of the UWP itself:
- easy distribution via the Microsoft Store (reachable for Windows 10 S Versions, too)
- easy and automatic updates via the store
- native compilations for the new Windows 10 on ARM versions
- usable on every Windows 10 device (PC, Tablets, Mobile, IoT and theoretically, but probably less useful Mixed Reality, Xbox)

Combined with Xamarin and/or .NET (Core) the full app could use one single code base in C# to provide native apps to all platforms, including UWP, iOS, Android and Linux.
So it might even reduce the amount of fragmentation :)

**Comment by RobertKrajewski** [comment]
The effort porting everything from C++ to C# would be higher than the time savings you mentioned.
