### ISSUE TITLE
Cannot sync to the same folder from OSes with different languages

### ISSUE THREAD

**Issue by LingMan** [RobertKrajewski/Sync-my-L2P#115]
I have a Linux/Windows dual boot setup and would like to be able to sync the L2P from both OSes into the same directory. The problem is that the Linux is in English while the Windows is in German.

Since Sync-my-L2P checks for the system language to determine the top level folder names (e.g. "Lernmaterialien" vs "StructuredMaterials"), it would duplicate my the entire L2P folder if I would sync under Linux on top of the Windows-created folder.
https://github.com/Sync-my-L2P/Sync-my-L2P/blob/cdaf64c61f995e91018fed36ee3977657dc7fb74/utils.cpp#L156

Some possible solutions:
1. Check for the application language instead of the system language. Easy but might unexpectedly break other user's setups.
2. Check if the top level folders already exist in another language. This would lead to mixed-language L2P folders once new course rooms get synced. Plus, it might still result in duplication unless all Sync-my-L2P installations which access that folder get updated.
3. Add a folder language setting next to the download location setting. Ideally this should be stored in a hidden file in the L2P folder, similar to the idea from https://github.com/Sync-my-L2P/Sync-my-L2P/issues/74, to ensure that the settings used by all Sync-my-L2P installations are identical.

To me option three looks the best as it is the only one that will not break any existing setups or lead to weirdnesses in the future.

**Comment by RobertKrajewski** [comment]
In my opinion, only a handful people sync the files using two different operating systems. Even less people use two different system languages. Therefore, I suggest, that you change the system language for Sync-my-L2P on Linux as e.g. described here: https://askubuntu.com/questions/79319/how-to-change-language-of-a-specific-application
