### ISSUE TITLE
AppImage does not work on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [RobertKrajewski/Sync-my-L2P#119]
`AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'CXXABI_1.3.8' not found`. Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems

Reference:
https://github.com/AppImage/appimage.github.io/pull/673

**Comment by probonopd** [comment]
Thanks for the trusty deb package. Would it be possible to also add an AppImage that was built on trusty?

**Comment by matu3ba** [comment]
@probonopd Could you test for version 2.4, if the problem still does occur?

**Comment by probonopd** [comment]
Thanks. By the way, it would be great if the filename could include the architecture, `x86_64`.

**Comment by probonopd** [comment]
Thank you. Added to AppImageHub.
