### ISSUE TITLE
Directory names are not createable (Moodle) (The : or . at the end)

### ISSUE THREAD

**Issue by Mayiaz** [RobertKrajewski/Sync-my-L2P#133]
ERROR 04:45:26.859 Directory not createable. :  Can not create the following directory: D:/L2P/ss18/Grundgebiete der Informatik 4/**Interessantes...**/Hackathon/ 

ERROR 04:45:26.863 Directory not setable:  D:/L2P/ss18/Grundgebiete der Informatik 4/**Interessantes...**/Hackathon/ 

ERROR 05:00:20.353 Directory not createable. :  Can not create the following directory: D:/L2P/ss18/Grundgebiete der Informatik 4/**Kapitel 1: Systemwerkzeuge**/Folien zu Kapitel 1/ 

ERROR 05:00:20.358 Directory not setable:  D:/L2P/ss18/Grundgebiete der Informatik 4/**Kapitel 1: Systemwerkzeuge**/Folien zu Kapitel 1/

**Comment by RobertKrajewski** [comment]
Fixed by 6bdb9495012c647b32f02948d89b9f3398add686
