### ISSUE TITLE
Handling of special characters in links and filepaths

### ISSUE THREAD

**Issue by RobertKrajewski** [RobertKrajewski/Sync-my-L2P#135]
Currently, special characters like "+" or "ü" are not correctly handled in links in filepath. This causes unreadable directory and filenames, or even prevents the download at all.

**Comment by Bergiu** [comment]
I will make a pull request later to fix this. Some parts are fixed server side, for example the endcoding of titles and modulenames and they will be available with the next api release.

**Comment by Bergiu** [comment]
We will make an api release tomorrow or the day after tomorrow. then the bug with downloading files that contains + and the bug with other special characters that are displayed wrong will be fixed. the commit i have made will fix the special characters on subfolders, after the release.

**Comment by Bergiu** [comment]
The changes on the api is deployed, so it should work with this fix.

**Comment by piet3** [comment]
Another Problem is that Moodle allows ":" in the names of topics. As it is not possible to create a folder with ":" in its name, Sync-my-L2P returns an error. It would be suffiecent, if Sync-my-L2P would just skip the Lehrveranstaltung and proceed. At the moment you can't use the program to download any files, if you have just a single Lehrveranstaltung that uses ":" in topics' name.

**Comment by Bergiu** [comment]
That depends on your filesystem. And I think it's already fixed with commit 6bdb9495012c647b32f02948d89b9f3398add686?
What could also be a problem are module or topic names, that differ only in there caps.

**Comment by Bergiu** [comment]
![image](https://user-images.githubusercontent.com/13796963/55551488-39428c80-56db-11e9-81f1-ae596364d171.png)
![image](https://user-images.githubusercontent.com/13796963/55551502-419ac780-56db-11e9-8c77-f00287f2d848.png)

In Moodle you can even create modules with the same name... And these 4 modules are displayed in the same folder in sync my l2p.

**Comment by piet3** [comment]
Ah okay, and is there even no problem if you change the topic to something like: "Part 1: General"?

**Comment by t-schroeder** [comment]
Seems like the issue with ":" only affects Windows. On Mac e.g. the ":" is replaced by a "/".

@piet3 Instead of skipping the entire Lehrveranstaltung when a topic with ":" in its name is encountered, why not replace it with another character instead? Otherwise Sync-my-L2P would only sync _some_ Lehrveranstaltungen and the user might not even notice that some are being skipped.

**Comment by t-schroeder** [comment]
Nevermind. I didn't realize this is already fixed.

**Comment by LdwgWffnschmdt** [comment]
Could you please release a new version with the ":" fix? It really makes the App unusable if you have one course with a colon in its name.
