### ISSUE TITLE
Remove trailing whitespaces from paths and filenames after shortening them

### ISSUE THREAD

**Issue by konsdibons** [RobertKrajewski/Sync-my-L2P#142]
long paths are getting shortened and sometimes end then with a whitespace which leads to errors in the file system.

for example: "Pretty Important Lecture [23.2355] (why not some more words)" gets shortened to "Pretty Important Lecture [23.2355] (why not some "

this is a problem for at least the windows filesystem.

**Comment by worsel22** [comment]
*Push

**Comment by kasnder** [comment]
Can confirm that this still persists, and it took some time to figure out how to remove the created folder.

Removing of the folder with spaces was not possible from the Windows exploder.

Yet, running good old WinRAR in admin mode allowed to fix the file system.

Would be great to have an update for this, if it isn’t a major effort from the programming side of things.
