### ISSUE TITLE
Remove special char (colon) from filename 

### ISSUE THREAD

**Issue by max0619** [RobertKrajewski/Sync-my-L2P#146]
File or folder cannot be created in Windows because it contains a colon ":" 
I get the error report:
```
"Verzeichnis nicht erstellbar!
Kann folgendes Verzeichnis nicht erstellen: C:/Users/Max/Downloads/L2Psync/ss19/Advanced Machine Learning (VO) [12.34452]/Exercis 2: Reinforcement Learning/Solution/"
```

 - OS: Windows 10
 - Version v2.4.0

**Comment by mwkroening** [comment]
This seems to be a duplicate of #135.

I suggest you to try again with [v2.4.1](https://github.com/RobertKrajewski/Sync-my-L2P/releases/tag/v2.4.1).

**Comment by max0619** [comment]
Thanks, fixed the problem.
