### ISSUE TITLE
Missing access right for single file stops synchronization

### ISSUE THREAD

**Issue by max0619** [RobertKrajewski/Sync-my-L2P#147]
A missing access right for a single file stops the whole synchronization

I get this error message:
```
Fehler beim Öffnen mit Schreibberechtigung
Exercise6*.pdf
```

**Desktop :**
 - OS: Windows 10
 - Version: v2.4.1

**Comment by RobertKrajewski** [comment]
This is the intended behavior. The idea behind this is, that many more errors are expected occur after the first one.
