### ISSUE TITLE
Create an organization and have some more people with higher rights

### ISSUE THREAD

**Issue by claell** [RobertKrajewski/Sync-my-L2P#155]
Currently this repo and especially the issues and PRs are only getting sporadic attention. This is probably because this whole project is only a side project and there is not always time to take care of it.

Since it is rather important for RWTH students and also linked on RWTH websites, it might be useful to create an organization for this where also RWTH developers are a part of.

**Comment by RobertKrajewski** [comment]
In the future the RWTH will handle the maintenance and further development of SyncMyL2P, as I will soon no longer be an employee at the RWTH. The transition is already taking place in this fork: https://github.com/rwthmoodle/Sync-my-L2P

**Comment by claell** [comment]
Thanks for letting me know. And thanks for all your great work for this Software, I really appreciate it!
