### ISSUE TITLE
PDF-Annotator file is not synchronised

### ISSUE THREAD

**Issue by Campenhausen** [RobertKrajewski/Sync-my-L2P#157]
One of our students reported, that the PDF files uploaded as PDF-Annotator in RWTHMoodle can not be synchronised. Would it be possible to add at least optinoal synchronisation of PDF-Annotator files?

**Comment by RobertKrajewski** [comment]
Thank you for this feature request. Unfortunately, this option is not provided by the API Sync-my-L2P has to use. Therefore, this feature can only be solved by extending the API itself.
