### ISSUE TITLE
Old L2P files are not on list to download. 

### ISSUE THREAD

**Issue by praneethkv** [RobertKrajewski/Sync-my-L2P#161]
I installed and logged in by providing credentials. It displays only files from new semesters(RWTH Moodle). Courses from old L2P are not displayed to download. I can view and open the files www3.elearning.rwth-aachen.de but not in the sync-my-L2P software
![image](https://user-images.githubusercontent.com/39022624/95224517-0b239880-07fb-11eb-8650-426ffdd70a84.png)
![image](https://user-images.githubusercontent.com/39022624/95224780-60f84080-07fb-11eb-80f4-d2926b3d9b0c.png)

Log:
Windows 10
INFO  17:34:59.735 This version is up to date  ( 20401 ) 

INFO  17:34:59.738 L2P Erreichbarkeitsrequest 

INFO  17:34:59.739 Moodle Erreichbarkeitsrequest 

INFO  17:34:59.913 L2P erreichbar 

INFO  17:34:59.913 Moodle erreichbar 

INFO  17:35:02.158 Veranstaltungen empfangen 

INFO  17:35:03.291 Moodle-Veranstaltungen empfangen 

INFO  17:35:06.300 Moodle-Veranstaltungen empfangen 

INFO  17:35:06.701 Veranstaltungen empfangen

**Comment by RobertKrajewski** [comment]
Have you tried to switch the option "Nur das aktuelle Semester anzeigen"?
This should solve your problem and make all files still available in L2P also available in Sync-my-L2P. If there are some courses missing, then those courses have been locked.

In case this shouldn't fix your problem, please post the extended log of the program
