### ISSUE TITLE
Little problem with the progress bar

### ISSUE THREAD

**Issue by claell** [RobertKrajewski/Sync-my-L2P#80]
When a sync starts the progress bar is replaced with a segment of elements behind it.

I hope you can see it in the screenshot.

![bildschirmfoto vom 2015-07-11 12 03 16](https://cloud.githubusercontent.com/assets/6171135/8633379/11f35f9a-27c5-11e5-80ee-e3e9bb91fd86.png)

**Comment by justin-time** [comment]
This is a known specific linux bug. Unfortunately, it is very hard to reproduce this bug because it occurs extreme rarely and not on a specific linux platform. 

Which Ubuntu version are you using at the moment? Ubuntu 15.04?

**Comment by claell** [comment]
Yes, I am using Ubuntu 15.04. For me it occurs every time I start a sync.

**Comment by claell** [comment]
This does not happen to me anymore on a current Ubuntu version. I guess it has been "fixed" in between somewhere, maybe because of Ubuntu using a different package for that.
