### ISSUE TITLE
Double listing of files

### ISSUE THREAD

**Issue by claell** [RobertKrajewski/Sync-my-L2P#96]
I noticed that some courses show two files with the same name. This results in one file not being able to be downloaded. It is always shown as new for me. I have this issue on at least two devices with the same two files.

![bildschirmfoto vom 2016-04-14 18-43-02](https://cloud.githubusercontent.com/assets/6171135/14536047/d1decfd4-0270-11e6-816e-35679de6305c.png)
![bildschirmfoto vom 2016-04-14 18-44-53](https://cloud.githubusercontent.com/assets/6171135/14536092/099ca446-0271-11e6-98b9-3d40cce3fdcd.png)

**Comment by Sync-my-L2P** [comment]
Since when does this problem occur? Are there also two files downloadable
in the l2p? Do the two files differ?
Am 14.04.2016 18:45 schrieb "Claudius Ellsel" <notifications@github.com>:

**Comment by claell** [comment]
I am experiencing this since a few moths and noticed this some time ago.

I just checked the L2P and there are two files from "Ankündigungen" with the same name. For example the second "Ankündigung" with the file merkblatt1-Aushang.pdf was added at 2015-02-09.

I don't know, whether the problem has already occured then.

The second file "Höörsaaleinteilung.pdf" was added in "Ankündigungen" on 2016-03-23.

**Comment by Sync-my-L2P** [comment]
So this is a general problem that files which are posted in Announcements can have an identical name. A solution would be to create subdirectories for each announcement. We will add this to the feature list.

**Comment by claell** [comment]
Alrigth, thanks.

**Comment by RobertKrajewski** [comment]
This bug won't be fixed anymore, as the moodle already suggests using a separate directory for each Ankündigung

**Comment by claell** [comment]
That is unfortunate, as it still is a problem for the (discontinued), but legacy supported L2P.
